repos:
  # Standard pre-commit hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      # Temporarily disabled due to IndexError bug with Git LFS files
      # - id: check-added-large-files
      #   args: ["--maxkb=1024"]
      #   exclude: '.*\.(bin|so|dll|exe|dylib)$'
      - id: check-merge-conflict
      - id: check-yaml
      - id: end-of-file-fixer

  # Python code formatting and linting
  - repo: local
    hooks:
      - id: black
        name: black
        description: Black code formatter
        entry: black
        language: system
        exclude: (?x)(^docs/|^thirdparty/|^projects/)
        files: \.(py)$
        types: [file, python]
        args: [--config=pyproject.toml]

      - id: isort
        name: isort
        description: Import sorting
        entry: isort
        language: system
        exclude: (?x)(^thirdparty/|^projects/)
        files: \.(py)$
        types: [file, python]
        args: [--settings-file=pyproject.toml]

      - id: pycodestyle
        name: pycodestyle
        description: PEP 8 style checking
        entry: pycodestyle
        language: system
        exclude: (?x)(^docs/|^thirdparty/|^scripts/build/|^projects/)
        files: \.(py)$
        types: [file, python]
        args: [--config=setup.cfg]

      - id: pydocstyle
        name: pydocstyle
        description: Python docstring style checking
        entry: pydocstyle
        language: system
        exclude: (?x)(^docs/|^thirdparty/|^projects/)
        files: \.(py)$
        types: [file, python]
        args: [--config=pyproject.toml]

# Optional: Commit message format checking
# Uncomment and run 'pre-commit install --hook-type commit-msg' to enable
# - repo: local
#   hooks:
#     - id: commit-check
#       name: check for commit msg format
#       language: pygrep
#       entry: '\A(?!(feat|fix|docs|style|refactor|perf|test|chore)\(.*\): (\[[a-zA-Z][a-zA-Z0-9_]+-[1-9][0-9]*\]|\[cr_id_skip\]) [A-Z]+.*)'
#       args: [--multiline]
#       stages: [commit-msg]
